id: hl7.fhir.uv.rtq-ig
canonical: https://build.fhir.org/ig/HL7/rtq-ig
name: RTQ_IG
title: Response to Regulatory Questions (RTQ)
description: The Response to Question (RTQ) Implementation Guide provides a standardized framework for the exchange of formal questions from health authorities to sponsors/applicants and structured responses in return.
status: draft
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: HL7 International
  url: http://www.hl7.org
license: CC0-1.0

pages:
  index.md:
    title: Home
  use-case.md:
    title: Use Case
  question.md:
    title: Question Structure
  questionex1.md:
    title: Question Example
  responseex1.md:
    title: Response Example
  response.md:
    title: Response Structure

menu:
  Home: index.html
  Use Case: use-case.html
  Question Structure: question.html
  Response Structure: response.html
  Artifacts: artifacts.html

resources:
  CodeSystem/ctd-categories-full:
    name: CTD Question Categories Full

  StructureDefinition/rtq-questionnaire:
    name: RTQ Regulatory Questionnaire (R5 Base)

  StructureDefinition/regulatory-questionnaire-narrative:
    name: Regulatory Questionnaire - Narrative Only

dependencies:
  hl7.fhir.r5.core: 5.0.0
  hl7.terminology.r5: 5.5.0
  hl7.fhir.uv.extensions.r5: 1.0.0
  hl7.fhir.pubpack: 0.2.3
  hl7.fhir.xver-extensions: 0.1.0