id: hl7.fhir.uv.rtq-ig
canonical: https://build.fhir.org/ig/HL7/rtq-ig
name: RTQ_IG
title: Response to Regulatory Questions (RTQ)
description: The Response to Question (RTQ) Implementation Guide provides a standardized framework for the exchange of formal questions from health authorities to sponsors/applicants and structured responses in return.
status: draft
version: 0.1.0
fhirVersion: 5.0.0
copyrightYear: 2025+
releaseLabel: ci-build
publisher:
  name: HL7 International
  url: http://www.hl7.org
license: CC0-1.0

pages:
  index.md:
    title: Home
  use-case.md:
    title: Use Case
  question.md:
    title: Question Profile & Example
  response.md:
    title: Response Profile & Example

menu:
  Home: index.html
  Use Case: use-case.html
  Question Structure: question.html
  Response Structure: response.html
  Samples:
    Question Sample: assets/question-sample.html
    Response Sample: assets/response-sample.html
  Artifacts: artifacts.html
